# Generated by Django 5.0.6 on 2026-08-04 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("summary", models.TextField(blank=True, default="")),
                ("simplified_text", models.TextField(blank=True, default="")),
                ("key_points", models.JSONField(default=list)),
                ("clauses", models.JSONField(default=list)),
                ("risks", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "model_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "db_table": "translations",
                "ordering": ["language"],
                "unique_together": {("document", "language")},
            },
        ),
    ]
