# Generated by Django 5.0.6 on 2026-08-04 16:46

import apps.documents.models
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("s3_key", models.CharField(max_length=1000)),
                ("s3_bucket", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.BigIntegerField()),
                ("page_count", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("validating", "Validating"),
                            ("extracting", "Extracting"),
                            ("chunking", "Chunking"),
                            ("analysing", "Analysing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "doc_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("legal", "Legal"),
                            ("medical", "Medical"),
                            ("government", "Government"),
                            ("financial", "Financial"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("target_language", models.CharField(default="en", max_length=10)),
                ("extracted_text", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.documents.models._expires_default
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("token_count", models.IntegerField(default=0)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "document_chunks",
                "ordering": ["chunk_index"],
            },
        ),
    ]
