# Generated by Django 5.0.6 on 2026-08-04 16:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("simplified_text", models.TextField(blank=True, default="")),
                (
                    "reading_level",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("flesch_kincaid_score", models.FloatField(blank=True, null=True)),
                ("key_points", models.JSONField(default=list)),
                ("clauses", models.JSONField(default=list)),
                ("risks", models.JSONField(default=list)),
                ("key_dates", models.JSONField(default=list)),
                ("word_count", models.IntegerField(blank=True, null=True)),
                ("prompt_version", models.CharField(default="v1", max_length=20)),
                (
                    "model_used",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "document_analyses",
            },
        ),
    ]
